// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StatusModelAPI is an autogenerated mock type for the StatusModelAPI type
type StatusModelAPI struct {
	mock.Mock
}

// SetStatusForEnvironment provides a mock function with given fields: repository, branch, status
func (_m *StatusModelAPI) SetStatusForEnvironment(repository string, branch string, status string) error {
	ret := _m.Called(repository, branch, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(repository, branch, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
